services:
  backend:
    environment:
      - QUARKUS_PROFILE=openai
      - QUARKUS_LANGCHAIN4J_CHAT_MODEL_PROVIDER=openai
      - QUARKUS_LANGCHAIN4J_EMBEDDING_MODEL_PROVIDER=openai
      - QUARKUS_LANGCHAIN4J_OPENAI_CHAT_MODEL_MODEL_NAME=gpt-4o-mini
      - QUARKUS_LANGCHAIN4J_OPENAI_EMBEDDING_MODEL_MODEL_NAME=text-embedding-3-small
      - QUARKUS_LANGCHAIN4J_PGVECTOR_DIMENSION=1536
      - QUARKUS_LANGCHAIN4J_OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
