services:
  db:
    build:
      context: ./db
    container_name: db-quanta
    ports:
      - 15432:5432
    environment:
      - POSTGRES_USER=quanta
      - POSTGRES_PASSWORD=not-secure
      - POSTGRES_DB=quanta
      - POSTGRES_HOST_AUTH_METHOD=trust
      - PGDATA=/var/lib/postgresql/data/pgdata
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U quanta -d quanta"]
      interval: 5s
      timeout: 3s
      retries: 5
    volumes:
      - ./db/data/:/var/lib/postgresql/data/
      - ./db/init:/docker-entrypoint-initdb.d

  backend:
    build:
      context: ./backend/
      dockerfile: Dockerfile.with-build
    container_name: backend-quanta
    depends_on:
      db:
        condition: service_healthy
    environment:
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://db-quanta:5432/quanta
      - QUARKUS_DATASOURCE_USERNAME=quanta
      - QUARKUS_DATASOURCE_PASSWORD=not-secure
      - QUARKUS_LANGCHAIN4J_OLLAMA_BASE-URL=http://host.docker.internal:12434
      - QUARKUS_LANGCHAIN4J_OLLAMA_EMBEDDING-MODEL_MODEL-NAME=qwen3-embedding:0.6B-F16
      - QUARKUS_LANGCHAIN4J_OLLAMA_CHAT-MODEL_MODEL-NAME=llama3.2:1B-Q8_0
      - QUARKUS_LANGCHAIN4J_LOG-REQUESTS=false
      - QUARKUS_LANGCHAIN4J_LOG-RESPONSES=false
      - QUANTA_FILESYSTEM_PATH=/app/resources/demo-files
    ports:
      - "8080:8080"
    models:
      - llm
      - embedding-model
    volumes:
      - ./resources/demo-files:/app/resources/demo-files

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend-quanta
    depends_on:
      - backend
    ports:
      - "3001:3000"

models:
  llm:
    model: ai/llama3.2:1B-Q8_0
  embedding-model:
    model: ai/qwen3-embedding:0.6B-F16
    runtime_flags:
      - "--embeddings"