services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama-quanta
    ports:
      - "11434:11434"
    volumes:
      - ./ollama/data:/root/.ollama
      - ./ollama/init:/init
    environment:
      - OLLAMA_KEEP_ALIVE=-1
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    entrypoint: [ "/bin/sh", "/init/run_ollama.sh" ]

  backend:
    build:
      context: ./backend/
      dockerfile: Dockerfile.with-build
    container_name: backend-quanta
    depends_on:
      ollama:
        condition: service_started
    environment:
      - QUARKUS_LANGCHAIN4J_OLLAMA_BASE-URL=http://ollama-quanta:11434
      - QUARKUS_LANGCHAIN4J_LOG-REQUESTS=false
      - QUARKUS_LANGCHAIN4J_LOG-RESPONSES=false
      - QUANTA_FILESYSTEM_PATH=/app/resources/demo-files
      - QUANTA_ECLIPSESTORE_STORAGE-PATH=/app/eclipsestore-data
    ports:
      - "8080:8080"
    volumes:
      - ./resources/demo-files:/app/resources/demo-files
      - ./eclipsestore-data:/app/eclipsestore-data

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend-quanta
    depends_on:
      - backend
    ports:
      - "3001:3000"
