quarkus.devservices.enabled=false
quarkus.langchain4j.ollama.base-url=http://localhost:11434
quarkus.langchain4j.ollama.embedding-model.model-name=qwen3-embedding:0.6b
quarkus.langchain4j.ollama.chat-model.model-name=llama3.2:1b
quarkus.langchain4j.neo4j.dimension=1024
quarkus.langchain4j.neo4j.label=FileMetadata
quarkus.langchain4j.log-requests=true
quarkus.langchain4j.log-responses=true
quarkus.langchain4j.ollama.timeout=3m
quarkus.langchain4j.neo4j.database-name=neo4j
quarkus.neo4j.uri=bolt://localhost:7687
quarkus.neo4j.authentication.username=neo4j
quarkus.neo4j.authentication.password=not-secure
quarkus.neo4j-ogm.packages=dev.rabauer.quanta.backend.storage
quarkus.http.cors.origins=*
quarkus.http.cors.methods=GET,POST,PUT,DELETE,OPTIONS
quarkus.http.cors.headers=Content-Type,Authorization